### PR TITLE
Use Ensaio to fetch the tutorial data

### LINKED ISSUE #2: Use Ensaio to fetch the tutorial data
The [gravity processing tutorial](https://github.com/fatiando/tutorials/blob/main/gravity-processing.ipynb) uses Pooch to fetch the datasets from the Zenodo archives at the start of the tutorial. This is good to showcase Pooch but we now have Ensaio for this. It would be good to start using it in the tutorial so we can test it out. 

A compromise between using Ensaio and showcasing Pooch would be to:

1. Use Ensaio to fetch some of the data. We load Southern Africa gravity, Earth topography, and Earth geoid. We could just get the topography and geoid with Ensaio for example.
2. Say that Ensaio uses Pooch under the hood and that, for example, you could load the Africa gravity data with Pooch as well. The text can mention `ensaio.fetch_southern_africa_gravity` and then show how to use `pooch.retrieve` to achieve the same thing. 

Or maybe we don't do this at all and just use Ensaio. We can then make a separate short tutorial just for Pooch.

Any thoughts/preferences on one of these options or **volunteers to implement the change** would be much appreciated ❤️

### PR DESCRIPTION
**Pull request by MGomezN**
Fixes #2 
Include a cell using Ensaio. Then, a Markdown section explaining that this could be done with Pooch to fetch any dataset.

**Reminders**:

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst` and the base `__init__.py` file for the package.
- [ ] Write detailed docstrings for all functions/classes/methods. It often helps to design better code if you write the docstrings first.
- [ ] If adding new functionality, add an example to the docstring, gallery, and/or tutorials.
- [ ] Add your full name, affiliation, and [ORCID](https://orcid.org) (optional) to the `AUTHORS.md` file (if you haven't already) in case you'd like to be listed as an author on the [Zenodo](https://zenodo.org/communities/fatiando) archive of the next release.

### CODE REVIEW

**Comment by MGomezN** [comment]
Hello! Not sure if I have to "Run make format and make check" for this contribution. However, I tried `conda install -c anaconda make` getting the _PackagesNotFoundError_. Also, it seems not available for [Windows](https://anaconda.org/anaconda/make). Anyways, if necessary, I will search for a solution :)

**Comment by santisoler** [comment]
This is looking great! Thanks @MGomezN ! :tada:

Thanks for adding `ensaio` to the `environment.yml` file and for making the changes in the notebook.

The only thing I would recommend is to rerun the entire notebook and then push it with all the outputs. You can always use the Run>Restart kernel and Rerun All Cells option.

> Not sure if I have to "Run make format and make check" for this contribution.

The checklist in the PR is inherited from `fatiando/.github` and it doesn't apply to every repo, being `tutorials` one of them. Sorry for that. I would only keep the one that reminds you to add yourself to the `AUTHORS.md` file.

> However, I tried conda install -c anaconda make getting the PackagesNotFoundError. Also, it seems not available for [Windows](https://anaconda.org/anaconda/make). Anyways, if necessary, I will search for a solution :)

You're right, apparently Anaconda dropped the `make` binaries for Windows (they used to provide them).
But, the good news is that `conda-forge` does provide them: https://anaconda.org/conda-forge/make

So, in order to install `make` on Windows you should run: `conda install -c conda-forge make`

Please, refresh my memory. Is there any place where we instruct people on installing `make` this way? It would be nice to update those instructions if we are providing them.

**Comment by leouieda** [comment]
@MGomezN thank you for making the change! I agree with @santisoler, this looks great and just needs a re-run.

Actually, there is a **very serious mistake** that needs to be fixed immediately. Your name is missing from the author list 😉

**Comment by leouieda** [comment]
About the checklist, I had opened a PR to make the organization wide template more general but it got lost in the holiday season: fatiando/.github#11 

@MGomezN would you mind taking a quick look at that PR to see if it would be a helpful template for a general pull request? Is there anything missing that you would have liked to be reminded when you open one?

**Comment by MGomezN** [comment]
Thanks for your comments!

> @MGomezN thank you for making the change! I agree with @santisoler, this looks great and just needs a re-run.

Deliberately I didn't run the cells for two reasons:
1) My awful/confusing paths:
C:\Users\maria\AppData\Local\ensaio\ensaio\Cache\v1\southern-africa-gravity.csv.xz
2) By including outputs, I got  "4,795 additions, 49 deletions not shown because the diff is too large." But I know I only made minor changes to the code, so numbers show no relevant differences. Therefore, I tried Jupytext. I generated a .py version of the notebook where only the appropriate changes to the code were reported and not all the info about the images in the outputs. But I still haven't perfectly understood how it works. That is why I erased the .py.

Now re-run is done

- [ ]

**Comment by MGomezN** [comment]
> Please, refresh my memory. Is there any place where we instruct people on installing `make` this way? It would be nice to update those instructions if we are providing them.

Sorry, I thought it was in the [Contributing Guidelines](https://github.com/fatiando/community/blob/main/CONTRIBUTING.md), but it is no, actually, under the phrase " Most repositories will also have a [Makefile](https://github.com/fatiando/community/blob/main/Makefile)" the link is broken. Maybe I got that command for one of the multiple options we tried when setting up my Windows machine to work with Boule.

Happily,`conda install -c conda-forge make` Was successful.

**Comment by leouieda** [comment]
Thanks, @MGomezN! You're right that it's not nice to have our personal paths in the notebook like that. I'm not sure if we can have a better solution right now apart from making this into a Jupyter Book or something like that. I opened #4 to discuss this. 

Merging this in!

**Pull request merged**
